version: '3.9'
services:
  next-app:
    build:
      dockerfile: dockerfile
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    # command: npm run dev
    environment:
      - NODE_ENV=development
      - AUTH_TRUST_HOST=true
      - AUTH_URL=http://localhost:3000
    restart: unless-stopped